name: Publish React

on:
  push:
    branches:
      - master
    paths:
      - 'apps/react-app/**'

jobs:
  build-and-publish:
    name: Build and Publish React App
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install pnpm
        run: npm i -g pnpm

      # - name: Install Dependencies
      #   run: pnpm install --filter @new/react-app
      # Install all dependencies in the monorepo recursively
      - name: Install Dependencies
        run: pnpm recursive install
        
      - name: Build React.js App
        run:  pnpm exec nx run @new/react-app:build

      - name: Deploy React.js App
        run: echo "Deploying React.js App..."
