name: Publish Next.js App

on:
  push:
    branches:
      - main
    paths:
      - 'apps/nextjs-app/**'

jobs:
  build-and-publish:
    name: Build and Publish Next.js App
    runs-on: [self-hosted, nextjs]  
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install --filter ./apps/nextjs-app...

      - name: Build Next.js App
        run: pnpm --filter ./apps/nextjs-app build

      - name: Publish to npm
        run: pnpm --filter ./apps/nextjs-app publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Deploy Next.js App
        run: echo "Deploying Next.js App..."
