name: Publish React

on:
  push:
    branches:
      - master
    paths:
      - 'apps/api/test-work-flow/*'
jobs:
  build-and-publish:
    name: Build and Publish React App
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install pnpm
        run: npm i -g pnpm

      # - name: Install Dependencies
      #   run: pnpm install --filter @new/web
      # Install all dependencies in the monorepo recursively
      - name: Install Dependencies
        run: pnpm recursive install
        
      - name: Build Next.js App
        run: pnpm --filter @new/test-work-flow build

      - name: Deploy Next.js App
        run: echo "Deploying Next.js App..."
